/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(hdlc_unstuff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(77398844994a06aff63b26f0e85b7b49)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <habets39/hdlc_unstuff.h>
// pydoc.h is automatically generated in the build directory
#include <hdlc_unstuff_pydoc.h>

void bind_hdlc_unstuff(py::module& m)
{

    using hdlc_unstuff    = gr::habets39::hdlc_unstuff;


    py::class_<hdlc_unstuff, gr::block, gr::basic_block,
        std::shared_ptr<hdlc_unstuff>>(m, "hdlc_unstuff", D(hdlc_unstuff))

        .def(py::init(&hdlc_unstuff::make),
           D(hdlc_unstuff,make)
        )
        



        ;




}








