/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_file_writer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d695cd6a9dd8c7ab488447b020eaa6dd)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <habets39/pdu_file_writer.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_file_writer_pydoc.h>

void bind_pdu_file_writer(py::module& m)
{

    using pdu_file_writer    = gr::habets39::pdu_file_writer;


    py::class_<pdu_file_writer, gr::block, gr::basic_block,
        std::shared_ptr<pdu_file_writer>>(m, "pdu_file_writer", D(pdu_file_writer))

        .def(py::init(&pdu_file_writer::make),
           D(pdu_file_writer,make)
        )
        



        ;




}








