/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tag2pdu.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5536db1e3a6299e5983519bed5febb41)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <habets39/tag2pdu.h>
// pydoc.h is automatically generated in the build directory
#include <tag2pdu_pydoc.h>

void bind_tag2pdu(py::module& m)
{

    using tag2pdu    = gr::habets39::tag2pdu;


    py::class_<tag2pdu, gr::block, gr::basic_block,
        std::shared_ptr<tag2pdu>>(m, "tag2pdu", D(tag2pdu))

        .def(py::init(&tag2pdu::make),
           D(tag2pdu,make)
        )
        



        ;




}








